apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastify-movies-jj
  name: fastify-movies-jj
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: fastify-movies-jj
  sessionAffinity: None
  type: LoadBalancer
