apiVersion: v1
kind: Service
metadata:
  annotations:
    azure-pipelines/jobName: '"BuildPushDeployDB"'
    azure-pipelines/org: https://dev.azure.com/ecomindo/
    azure-pipelines/pipeline: '"Ec.BE.Node.Template"'
    azure-pipelines/pipelineId: '"255"'
    azure-pipelines/project: Specialist Programme
    azure-pipelines/run: "20210716.4"
    azure-pipelines/runuri: https://dev.azure.com/ecomindo/Specialist Programme/_build/results?buildId=4422
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"fastify-ts-db"},"name":"fastify-ts-db","namespace":"default"},"spec":{"ports":[{"port":3001}],"selector":{"app":"fastify-ts-db"},"type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2021-07-15T08:34:17Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: fastify-ts-db
  name: fastify-ts-db
  namespace: default
  resourceVersion: "171516"
  selfLink: /api/v1/namespaces/default/services/fastify-ts-db
  uid: 5bbd16ae-b170-4da0-aa11-8816a8931d6a
spec:
  clusterIP: 10.0.7.251
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31675
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: fastify-ts-db
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.44.249.184
