apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"fastify-movies-jj"},"name":"fastify-movies-jj","namespace":"jj"},"spec":{"ports":[{"nodePort":30036,"port":3001,"protocol":"TCP","targetPort":3001}],"selector":{"app":"fastify-movies-jj"},"sessionAffinity":"None","type":"LoadBalancer"}}
    creationTimestamp: "2021-07-25T11:36:28Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: fastify-movies-jj
    name: fastify-movies-jj
    namespace: jj
    resourceVersion: "1927374"
    selfLink: /api/v1/namespaces/jj/services/fastify-movies-jj
    uid: 88628005-2ea5-4265-9629-6bf6f88cf489
  spec:
    clusterIP: 10.0.23.90
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30036
      port: 3001
      protocol: TCP
      targetPort: 3001
    selector:
      app: fastify-movies-jj
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 104.43.72.191
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
